// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
import static org.junit.Assert.*;

public class FinishSaleTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void finishSale() {
    driver.get("http://localhost:3000/products/cart");
    driver.findElement(By.cssSelector(".product-buy-btn")).click();
    driver.findElement(By.cssSelector(".register-form-btn")).click();
    sleep();
    assertEquals("Criado com sucesso!", driver.findElement(By.cssSelector(".swal-text")).getText());
    String resultado = driver.findElement(By.cssSelector(".swal-text")).getText();
    String resuEsperado = "Criado com sucesso!";
    System.out.println("O resultado foi: " + resultado + "\n" + "O resultado esperado era: " + resuEsperado);
    driver.findElement(By.cssSelector(".swal-button")).click();
  }

  public void sleep() {
    try {
      Thread.sleep(3000); // espera por 3 segundos
    } catch (InterruptedException e) {
      // tratar a exceção, se necessário
    }
  }
}
