
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class RegisterMovieTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void registerMovie() {
    driver.get("http://localhost:3000/movies/register");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.cssSelector(".wrap-register:nth-child(1) > .wrap-input:nth-child(1) > .input-register-form"))
        .click();
    driver.findElement(By.cssSelector(".wrap-register:nth-child(1) > .wrap-input:nth-child(1) > .input-register-form"))
        .sendKeys("Todo mundo em pânico 3");
    driver.findElement(By.cssSelector(".wrap-register:nth-child(3) > .wrap-input:nth-child(1) > .input-register-form"))
        .click();
    {
      WebElement dropdown = driver
          .findElement(By.cssSelector(".wrap-register:nth-child(3) > .wrap-input:nth-child(1) > .input-register-form"));
      dropdown.findElement(By.xpath("//option[. = '18']")).click();
    }
    driver.findElement(By.cssSelector(".wrap-register:nth-child(3) > .wrap-input:nth-child(2) > .input-register-form"))
        .click();
    {
      WebElement dropdown1 = driver
          .findElement(By.cssSelector(".wrap-register:nth-child(3) > .wrap-input:nth-child(2) > .input-register-form"));
      dropdown1.findElement(By.xpath("//option[. = 'Sim']")).click();
    }
    driver.findElement(By.cssSelector(".wrap-register:nth-child(3) > .wrap-input:nth-child(4) > .input-register-form"))
        .click();
    driver.findElement(By.cssSelector(".wrap-register:nth-child(3) > .wrap-input:nth-child(4) > .input-register-form"))
        .sendKeys("English");
    driver.findElement(By.cssSelector(".textarea")).click();
    driver.findElement(By.cssSelector(".textarea")).sendKeys(
        "Depois de a repórter de jornal Cindy assistir acidentalmente uma estranha fita de vídeo que faz com que o espectador morra dentro de uma semana, ela descobre que a fita é apenas um dos muitos acontecimentos estranhos recentes.");
    driver.findElement(By.cssSelector(".wrap-register:nth-child(1) > .wrap-input:nth-child(3) > .input-register-form"))
        .click();
    driver.findElement(By.cssSelector(".wrap-register:nth-child(1) > .wrap-input:nth-child(3) > .input-register-form"))
        .sendKeys("180");
    driver.findElement(By.cssSelector(".wrap-register:nth-child(1) > .wrap-input:nth-child(2) > .input-register-form"))
        .click();
    sleep();sleep();sleep();
    /*driver.findElement(By.cssSelector(".wrap-register:nth-child(1) > .wrap-input:nth-child(2) > .input-register-form"))
        .sendKeys("07/02/2023:04:04");*/

    driver.findElement(By.cssSelector(".container-register")).click();
    driver.findElement(By.cssSelector(".legenda")).sendKeys("Sim");
  
    driver.findElement(By.cssSelector(".wrap-input:nth-child(5) > .input-register-form")).click();
    driver.findElement(By.cssSelector(".wrap-input:nth-child(5) > .input-register-form")).sendKeys(
        "https://s2.glbimg.com/mJo7vJOxxZh4qMh-46r-Pn481k8=/362x536/https://s2.glbimg.com/V4boHoY1HEmDW2IvDKugnEjbfcI=/i.s3.glbimg.com/v1/AUTH_c3c606ff68e7478091d1ca496f9c5625/internal_photos/bs/2022/3/H/n9ZtqsRGq50dWdYYBnCw/2022-2965-todo-mundo-em-panico-3-poster.jpg");
    driver.findElement(By.cssSelector(".register-form-btn")).click();
    sleep();
    sleep();
    driver.findElement(By.cssSelector(".dropdown-item:nth-child(1)")).click();
    sleep();
    driver.findElement(By.cssSelector(".swal-button")).click();
    sleep();
    sleep();
    driver.findElement(By.cssSelector(".register-form-btn")).click();
    
    sleep();
    sleep();
    sleep();
    String resultado = driver.findElement(By.cssSelector(".movie-list-item:nth-child(9) .movie-list-item-title")).getText();
    String resuEsperado = "TODO MUNDO EM PÂNICO 3";
    assertEquals("TODO MUNDO EM PÂNICO 3", driver.findElement(By.cssSelector(".movie-list-item:nth-child(9) .movie-list-item-title")).getText());
    System.out.println("O resultado foi: " + resultado + "\n" + "O resultado esperado era: " + resuEsperado);
  }

  public void sleep() {
    try {
      Thread.sleep(2000); // espera por 3 segundos
    } catch (InterruptedException e) {
      // tratar a exceção, se necessário
    }
  }
}
